
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuJFrame.java
 *
 * Created on Jun 18, 2014, 12:45:31 AM
 */
/**
 *
 * @author PROF AKINYOKUN
 */
public class MenuJFrame extends javax.swing.JFrame {
     Connection conn = null ;
     private String PcMode , ImagePath; 

    /** Creates new form MenuJFrame */
    public MenuJFrame()  {
        initComponents();
    this.setSize(1200, 800);
    this.setResizable(false);
                  final Toolkit toolkit = Toolkit.getDefaultToolkit();
    final Dimension screenSize = toolkit.getScreenSize();
    final int x = (screenSize.width - this.getWidth()) / 2;
    final int y = (screenSize.height - this.getHeight()) / 2;
    this.setLocation(x, y);
         this.getContentPane().setBackground(Color.white);
         setIcon() ; 
         
     	
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Banner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcome = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        b = new javax.swing.JCheckBox();
        a = new javax.swing.JCheckBox();
        e = new javax.swing.JCheckBox();
        c = new javax.swing.JCheckBox();
        i = new javax.swing.JCheckBox();
        h = new javax.swing.JCheckBox();
        g = new javax.swing.JCheckBox();
        f = new javax.swing.JCheckBox();
        d = new javax.swing.JCheckBox();
        begin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FAKOB");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(txtDate);
        txtDate.setBounds(1482, 0, 138, 23);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REAPING REWARD");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1250, 30);

        Banner.setBackground(new java.awt.Color(255, 255, 255));
        Banner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Image20.png"))); // NOI18N
        Banner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, -1));

        welcome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Banner.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Image4.png"))); // NOI18N
        Banner.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Image9.png"))); // NOI18N
        Banner.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        b.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b.setText("           Reduce Stress");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        Banner.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        a.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a.setText("          Weight Management");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        Banner.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        e.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e.setText("          Improve Strenght & Stamina");
        Banner.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c.setText("           Improve Hydration");
        Banner.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        i.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        i.setText("          A Healthy You");
        Banner.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, -1, -1));

        h.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h.setText("          Financial");
        Banner.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, -1, -1));

        g.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        g.setText("          Emotional Wellbeing");
        Banner.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        f.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f.setText("          Quit Smoking");
        Banner.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, -1, -1));

        d.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        d.setText("           Work/Life Balance");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        Banner.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        begin.setBackground(new java.awt.Color(0, 0, 51));
        begin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beginMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BEGIN");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        begin.add(jLabel13);

        Banner.add(begin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 240, 30));

        getContentPane().add(Banner);
        Banner.setBounds(0, 0, 1170, 740);

        jMenu5.setText("               ");
        jMenuBar1.add(jMenu5);

        jMenu10.setText("               ");
        jMenuBar1.add(jMenu10);

        jMenu15.setText("               ");
        jMenuBar1.add(jMenu15);

        jMenu20.setText("               ");
        jMenuBar1.add(jMenu20);

        jMenu25.setText("               ");
        jMenuBar1.add(jMenu25);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                                
                // TODO add your handling code here:
                              conn = (Connection) mysqlconnect.ConnectDb();
                              welcome.setText("Welcome "+firstname);
                             
                            
}//GEN-LAST:event_formWindowOpened

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel13MouseClicked

    private void beginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beginMouseClicked
        // TODO add your handling code here:
       
        conn = (Connection) mysqlconnect.ConnectDb();
        boolean checkeda = a.isSelected();
          boolean checkedb = b.isSelected();
            boolean checkedc = c.isSelected();
              boolean checkedd = d.isSelected();
                boolean checkede = e.isSelected();
                  boolean checkedf = f.isSelected();
                    boolean checkedg = g.isSelected();
                      boolean checkedh = h.isSelected();
                        boolean checkedi = i.isSelected();
                        
        
                         boolean matter[] = new boolean[9] ;
          matter[0] = checkeda ;
          matter[1] = checkedb ;
               matter[2] = checkedc;
                 matter[3] = checkedd;
                   matter[4] = checkede;
                     matter[5] = checkedf;
                       matter[6] = checkedg;
                         matter[7] = checkedh;
                           matter[8] = checkedi;
               
                 
                               String info[] = new String[3] ;
           info[0] = email ;
           info[1] = firstname;
               info[2] =lastname ;
                           
                           
                 Weight.main(info,matter);
               
    //     JOptionPane.showMessageDialog(null,checked) ;
      
    }//GEN-LAST:event_beginMouseClicked
public static String email,firstname,lastname ;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        email = args[0];
        firstname =  args[1];
        lastname =  args[2]  ;
		        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               new MenuJFrame().setVisible(true);
                
            }
        });    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JCheckBox a;
    private javax.swing.JCheckBox b;
    private javax.swing.JPanel begin;
    private javax.swing.JCheckBox c;
    private javax.swing.JCheckBox d;
    private javax.swing.JCheckBox e;
    private javax.swing.JCheckBox f;
    private javax.swing.JCheckBox g;
    private javax.swing.JCheckBox h;
    private javax.swing.JCheckBox i;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtDate;
    private javax.swing.JButton welcome;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo.jpg"))) ;
    }
}
